Mobile Devices Configuration Guide
==================================
////

    This file is part of the SOGo project.

    See includes/global-attributes.asciidoc
    for authors, copyright and license information.

////
include::includes/global-attributes.asciidoc[]

About this Guide
----------------

This guide explains how to configure calendar and contact
synchronization on Apple iOS devices (iPhone, iPod touch, and iPad)
using the native CalDAV and CardDAV support.

For devices synchronizing over the Microsoft ActiveSync protocol,
refer to the "Microsoft Enterprise ActiveSync" section of the SOGo
Installation Guide.

The instructions are based on version {release_version} of SOGo.

The latest version of this guide is available at
https://www.sogo.nu/support.html#/documentation.

Introduction
------------

SOGo is a free and modern scalable groupware server. It offers shared
calendars, address books, and emails through your favourite Web browser
and by using a native client such as Mozilla Thunderbird.

SOGo is standard-compliant. It supports CalDAV, CardDAV, GroupDAV, iMIP
and iTIP and reuses existing IMAP, SMTP and database servers - making
the solution easy to deploy and interoperable with many applications.

SOGo features:

* Scalable architecture suitable for deployments from dozen to many
thousand users
* Rich Web-based interface that shares the look and feel, the features
and the data of Mozilla Thunderbird
* Improved integration with Mozilla Thunderbird by using
the SOGo Connector and the SOGo Integrator
* Two-way synchronization support with any Microsoft ActiveSync-capable
device, or Outlook 2013

SOGo is developed by a community of developers located mainly in North
America and Europe. More information can be found on
http://www.sogo.nu/.

Apple iOS — Calendars
---------------------

Starting from iOS 3, Apple has added CalDAV support to the calendar
application included in the iPhone/iPod/iPad.

To add a CalDAV account, follow those instructions:

* From the _Settings_ menu, choose _Mail, Contacts, Calendars_
* Choose _Add Account..._
* Choose _Other_
* Choose _Add CalDAV Account_
* Specify the _Server_, the URL should be
  `http://sogo.domain.com/SOGo/dav/<username>`

On iOS 3.1.2 and later, you must also specify the range of events you
want to have. 

* From the _Settings_ menu, choose _Mail, Contacts, Calendars_
* From the _Sync_ menu, choose _All Events_

Note that other options (_Events 2 Weeks Back_, etc.) do not work right
now.

Apple iOS — Contacts
--------------------

If you want to synchronize contacts with your Apple mobile device, use
the native address book application with SOGo using the CardDAV
protocol. To configure the address book application so it works with
SOGo, create a new CardDAV account and specify your server name.

include::includes/additional-info.asciidoc[]

include::includes/commercial-support.asciidoc[]
